### ISSUE TITLE
Installer version for 1.6.16.509

### ISSUE THREAD

**Issue by JoelCanteroGCO** [RNoeldner/CSVQuickViewer#13]
Hello @RNoeldner,

First of all, thank you very much for creating this useful tool. I am working as a Data Scientist and all of my mates use this software to read CSV. We think that your app is the best CSV reader :)

I have just one question: could you upload a installer version for your last release (1.6.16.509)?

Thank you very much,
Joel

**Comment by RNoeldner** [comment]
I did have some trouble with the installer as that needed to have .NET 5 installed which filed on my computer until I did a brand new Windows installation.
The next release will have a the  installer again. This installer does not do that much though... the application itself should work as long as you have the executable and the .NET framework 4.72 installed.

**Comment by RNoeldner** [comment]
New release with installer published
