### ISSUE TITLE
Trojan:Win32/Wacatac.H!ml in exe release

### ISSUE THREAD

**Issue by gusman80** [RNoeldner/CSVQuickViewer#17]
hei windows 10 alarms Trojan:Win32/Wacatac.H!ml in your latest exe release this morning :(

**Comment by RNoeldner** [comment]
I had been looking into this for some time now, it's failed some checks through virustotal. 
The latest release stilled only showed an issue for the .NET6 installation., so I decided to not include this installation anymore.
Only version available now are .NET 4.72 and .Net 7
If you do not trust the installer, please use the portable zip.

**Comment by RNoeldner** [comment]
Pleese check new release
