### ISSUE TITLE
Could not load file or assembly BouncyCastle.Crypto

### ISSUE THREAD

**Issue by rafastryk** [RNoeldner/CSVQuickViewer#24]
Hi, after installing the latest version I get an Error:
`Could not load file or assembly 'BouncyCastle.Crypto, Version=1.9.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942'`

**Comment by saalkom** [comment]
Can confirm this on 1.7.5.582 and 1.7.8.589; haven't tested earlier versions.

**Comment by RNoeldner** [comment]
Sorry for this inconvenience, this is beings addressed in V1.7.9
