### ISSUE TITLE
Resize rows with Linefeeds

### ISSUE THREAD

**Issue by SurfingSpider** [RNoeldner/CSVQuickViewer#25]
Is there a way to resize rows to show the full contents when you use line feed in the cells?

I have a program that is producing a CSV report and would like to not have to resize rows on opening?

Example file [FTB_MOTD2_231006_CHRIWOLS_ICM-v1.csv](https://github.com/RNoeldner/CSVQuickViewer/files/12846805/FTB_MOTD2_231006_CHRIWOLS_ICM-v1.csv)

**Comment by RNoeldner** [comment]
There is a processing of the row height but it does not work very well, right now as a linefeed is seen it tries to increase the row size but only by a bit so you at least have the chance to see that there is something... 
Measurement of the height depending on shown  text the font and and column with is something I do shy away of, sorry.
