### ISSUE TITLE
Code Change

### ISSUE THREAD

**Issue by EngineControls** [RNoeldner/CSVQuickViewer#7]
Hi there, i trust you are well. I am using your code to view log files. 
How can i change / where should i change the code so that users cannot edit the data. 

Basically i do not want them to be able to double click in a field and edit the data. 

Kind regards

**Comment by EngineControls** [comment]
Another question while im on here, would it be able to add a print feature? 
So that we can simply press print from within the software and print.

**Comment by RNoeldner** [comment]
Hello Engine Control, to edit select the  cell and click on it once more or press F2 you should see that you can change the value.
If you double click on it it it only select the cell. 

As for printing,I will have a look , I did usually copy and paste it to Microsoft Excel for printing.
