### ISSUE TITLE
V1.6.11.493 Go to end of file = exception

### ISSUE THREAD

**Issue by JensKDK** [RNoeldner/CSVQuickViewer#9]
![Exception](https://user-images.githubusercontent.com/35413656/114543221-30390e00-9c59-11eb-991c-76c15065339a.png)

**Comment by RNoeldner** [comment]
I will look into this

**Comment by RNoeldner** [comment]
Can you please give it another try, I hope its fixed now I have refactored a lot of UI code hoping to fix issues like this
